eureka:
  instance:
    hostname: localhost
    ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8888
spring:
  application:
    name: eureka